### ISSUE TITLE
how can I paginate?

### ISSUE THREAD

**Issue by jbmurphy** [Balancingrock/classic-jekyll-theme#12]
I am trying to learn Jekyll and I can't figure out how to paginate. Any suggestions?
Off the home page, once I get to number-of-posts-on-home-page, I can't find a way to add a previous?

Thanks.

**Comment by Balancingrock** [comment]
I have never used pagination, so I am afraid that I cannot help there. There is build-in support for pagination in Jekyll though: https://jekyllrb.com/docs/pagination/#enable-pagination

But as I said, I have not used that so I do not know if it works with the theme. The 'number-of-posts-on-home-page' was added when Jekyll did not support pagination reliably.

In edit: Now that I read the jekyll documentation(see above) it seems to me that the number-of-posts-on-home-page should probably be removed from the home-layout. And then simply use the pagination as described in the jekyll documentation.

What do you mean with "I can't find a way to add a previous?"

**Comment by jbmurphy** [comment]
I can't figure out how to add "previous x number of posts." links

Thanks though.

**Comment by Balancingrock** [comment]
Ah, you can probably use the "_includes/widgets/recent-posts.html" as an example for that.
