### ISSUE TITLE
Use of "menuInclude: no" overrides landing page if filename alphabetically less-than

### ISSUE THREAD

**Issue by dcrossleyau** [Balancingrock/classic-jekyll-theme#13]
We have some pages that are not linked into the navigation menus, yet should appear to belong to a certain area of the site. So their relevant menu area should be highlighted in the top horizontal menubar, and that area's left-hand vertical menu should be shown.

This can be achieved with frontmatter "menuInclude: no".

However there seems to be a glitch.

To demonstrate with the test "pages" ...

Add this file [not-in-menu.md](https://github.com/Balancingrock/classic-jekyll-theme/files/1645383/not-in-menu.md.txt) to the `/pages/menus/` directory. It has this frontmatter:

```
---
layout: page
menuInclude: no
menuTopTitle: Menus
---
```

Now visit the URL "/pages/menus/not-in-menu.html" ... That works as intended: The "Menus" area is highlighted.

Now add this file [is-not-in-menu.md](https://github.com/Balancingrock/classic-jekyll-theme/files/1645382/is-not-in-menu.md.txt) to the `/pages/menus/` directory. It has the same frontmatter. It too highlights the "Menus" area as intended.

However, here is the glitch ...

The "Menus" item has a "landing page" configured, i.e. "landing-page.md". Adding this new page "is-not-in-menu" causes it to become the landing page instead.

Any filename that sorts alphabetically less than the filename of the configured landing page will be broken in this way. Any filename that sorts alphabetically greater is okay. So for example "l.md" is broken, whereas "lam.md" is okay.

Perhaps the landing page should only be selected from the set of pages that have the frontmatter "menuTopTitle: Menus" and "menuInclude: yes".

**Comment by Balancingrock** [comment]
Thanks, I have corrected the selection algorithm for the landing page.

The fix also illustrated an opportunity for a minor performance improvement which I also implemented.

V2.1.0 will be released shortly.

**Comment by dcrossleyau** [comment]
Thanks. That works beautifully.
