### ISSUE TITLE
Scroll code section

### ISSUE THREAD

**Issue by fedemengo** [Balancingrock/classic-jekyll-theme#14]
Is there a way to display long lines of code keeping it inside the central column border? When I write code that is too long it doesn't automatically embed it within a some sort of scroll view. 

Thank you, great work!

**Comment by Balancingrock** [comment]
You can add a scrollbar to the code by adding _overflow-x: auto;_ to the _.highlight_ SCSS class.

Though the _.highlight_ class is defined in `_sass/classic/_syntax-highlighting.scss`, I'd suggest you add the following lines to the end of `_sass/classic/_custom.scss`:

    .highlight {
        overflow-x: auto;
    }

**Comment by Balancingrock** [comment]
Assumed closed.
