### ISSUE TITLE
youtube-player widget

### ISSUE THREAD

**Issue by 5shekel** [Balancingrock/classic-jekyll-theme#15]
first of all, thank you for the theme
you documentation, code comments, and scss re-structuring (class-Jekyll-theme.scss!!) made me a flatCMS believer once more!

i don't have an actual issue. just wanted to let you know :+1: 

oh, maybe one thing.

i've added a max-width:800px to the _widgets.scss iframe-wrapper-hd section. 
to stop the expanding of videos (and iframes). you mention a padding alternative on the youtube-play.htm but i couldn't figure that one out. 

and if you ever need electronics help :)

**Comment by Balancingrock** [comment]
Thank you.

The padding does not help in stopping the expansion, so you were quite right in your solution.

Turns out, I know a bit about electronics myself... :-)
