### ISSUE TITLE
Open the relevant sub-menu when visiting one of its sub-sub-items (with vertical-menu)

### ISSUE THREAD

**Issue by dcrossleyau** [Balancingrock/classic-jekyll-theme#17]
We have a set of tutorials, with each one having multiple pages (one for each lesson).

When viewing one of the lesson pages, its parent sub-menu disclosure indicator remains closed. Would it be possible for it to be displayed open when viewing one of its sub-sub-menu item pages?

There is a minimal demonstration attached here as [tutorials.tar.gz](https://github.com/Balancingrock/classic-jekyll-theme/files/1684212/tutorials.tar.gz) -- unpack that to the top-level of the test site. Configure "drop-down-menu: no" and visit the "Tutorials" menu.

Visit the URL /tutorials/tutorial-1/lesson-1/

Now select the disclosure indicator to open the "Tutorial 1" sub-menu. The "Lesson 1" sub-sub-item is already highlighted, as desired.

Now visit "Lesson 2". The "Tutorial 1" sub-menu is now closed again, and so the context of where we are located in the menu structure is hidden.

**Comment by Balancingrock** [comment]
First thought is that it is not possible in the way the tutorials demonstration is implemented. Jekyll generates the site a page at a time, and each page becomes a self-contained output, i.e. all the information necessary to output the webpage must be present in the originating page. Currently the `lesson 1.md` (and the others as well) in the tutorials can only be linked to the menu through the menuTopTitle. The information about the menu sub title is not present.

If Liquid were a normal programming language I think it would be possible to use the URL to link to the menu structure, but as Liquid has very limited capabilities I fear this is not a viable option.

When I try to introduce the menuSubs into the `lesson` files the menu structure becomes garbled. Still, I think that would be the way to go, and will investigate how much effort that would require.

**Comment by Balancingrock** [comment]
HEAD should now implement this feature.
I will add an example and updated documentation tomorrow.

**Comment by Balancingrock** [comment]
Turns out, using the URL works quite well, even in Liquid. So it is not necessary to specify the subsub menu items in their own file.

A version 2.2.0 of classic will be released later today.

**Comment by dcrossleyau** [comment]
Oh very nice. Upgrading made it work immediately for us. Thanks too for the examples.
