### ISSUE TITLE
The banner icon not shown in Firefox, okay in Safari and Chrome

### ISSUE THREAD

**Issue by dcrossleyau** [Balancingrock/classic-jekyll-theme#19]
The banner icon in the top-left is not displayed with Firefox browser, both on macOS and on Linux.

All is well in both Safari and Chrome.

See for example:
http://balancingrock.github.io/classic-jekyll-theme

**Comment by Balancingrock** [comment]
Indeed. I will look into this, but probably not before the next week.

**Comment by Balancingrock** [comment]
Oh, that was easier than expected, its a known problem in Firefox.
HEAD has been updated to fix this, a date for release 2.4.0 has not been set yet.

**Comment by dcrossleyau** [comment]
Thanks.

**Comment by dcrossleyau** [comment]
Re-opened. There is a similar issue for the "menubar-icon".

**Comment by dcrossleyau** [comment]
Fixed. Thanks.
