### ISSUE TITLE
The gem is missing file navbanner.md

### ISSUE THREAD

**Issue by dcrossleyau** [Balancingrock/classic-jekyll-theme#2]
Installed v1.9.0 via Gem. The setup instructions say to copy "navbanner.md" from the Gem. However that file is missing.

**Comment by Balancingrock** [comment]
Confirmed.

I will update the gem once I get back.
Workaround: Create the file manually with the following content

    ---
    layout: navbanner-layout
    ---

or copy the file from github.

**Comment by Balancingrock** [comment]
Release 1.9.1 released to fix this issue.
