### ISSUE TITLE
List this theme as an available remote theme

### ISSUE THREAD

**Issue by dcrossleyau** [Balancingrock/classic-jekyll-theme#9]
The GitHub blog recently [announced](https://github.com/blog/2464-use-any-theme-with-github-pages) the ability to use any theme as a "remote-theme" (actually a recent Jekyll new feature). That works nicely for classic-jekyll-theme. The [jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme) README explains.

That blog post links to the set of "community-curated themes" by using a Topic search for "jekyll-theme". The "classic-jekyll-theme" is not currently listed there.

Need to use the GitHub "add topics" link under the repository description to add at least "jekyll-theme".

**Comment by Balancingrock** [comment]
Thanks for the heads up.
Jekyll-theme topic has been added.

**Comment by dcrossleyau** [comment]
Listed now. Thanks.
